name: decla_time
description: "An app for keeping track of your short-term rentals."


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.2

  internet_connection_checker: ^1.0.0+1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Do Hyeon
      fonts:
        - asset: fonts/DoHyeon-Regular.ttf
    - family: Ysabeau
      fonts:
        - asset: fonts/Ysabeau-Regular.ttf
  
